name: pandas
dependencies:
  - Cython
  - matplotlib
  - numexpr
  - nomkl
  - numpy
  - python=3
  - python-dateutil
  - pytz
  - scipy
  - sqlalchemy
  - pip:
    - git+https://github.com/spacetelescope/asv
